<script lang="ts">
	let {
		src = '',
		alt = '',
		loading = 'lazy',
		fetchPriority = 'auto',
		class: className = '',
		sizes,
		maxWidth = 960
	} = $props<{
		src?: string;
		alt?: string;
		loading?: 'lazy' | 'eager';
		fetchPriority?: 'high' | 'low' | 'auto';
		class?: string;
		sizes?: string;
		maxWidth?: number; // e.g. 640 for cards, 960 for hero
	}>();
	function altFromSrc(src) {
		return src
			.split('/')
			.pop()
			.replace(/\.[^.]+$/, '')
			.replace(/[-_]+/g, ' ')
			.replace(/\s+/g, ' ')
			.trim();
	}

	// Import intrinsic sizes generated by the Node script
	// (file written to src/lib/image-sizes.json)
	// eslint-disable-next-line @typescript-eslint/ban-ts-comment
	// @ts-ignore
	import imageMeta from '$lib/image-sizes.json';

	type ImageMeta = Record<string, { width: number | null; height: number | null }>;

	const metaMap = imageMeta as ImageMeta;

	// Find metadata by the original src (e.g. "/uploads/memes/foo.jpg")
	const meta = metaMap[src] ?? null;

	const intrinsicWidth = meta?.width ?? 640;
	const intrinsicHeight = meta?.height ?? 360;

	// Strip extension: /uploads/foo.jpg → /uploads/foo
	const base = src.replace(/\.[^.]+$/, '');

	// All generated widths from your image script
	const ALL_WIDTHS = [320, 640, 960] as const;

	// Filter by maxWidth so you can reuse the component everywhere
	const widths = ALL_WIDTHS.filter((w) => w <= maxWidth && w <= intrinsicWidth);

	// Safety net: if someone passed maxWidth < 320, fall back to smallest
	const effectiveWidths = widths.length > 0 ? widths : [ALL_WIDTHS[0]];

	const avifSrcset = effectiveWidths.map((w) => `${base}.${w}.avif ${w}w`).join(', ');

	const webpSrcset = effectiveWidths.map((w) => `${base}.${w}.webp ${w}w`).join(', ');

	// Fallback JPG (only 640 exists from your script)
	//	const jpgFallback = `${base}.640.jpg`;

	// Safe default; you can override with `sizes` prop
	const defaultSizes = '(min-width: 1200px) 25vw, (min-width: 768px) 33vw, 100vw';
</script>

<img
	class={className}
	srcset={webpSrcset}
	sizes={sizes ?? defaultSizes}
	src={jpgFallback}
	alt={altFromSrc(src)}
	loading={loading ?? undefined}
	fetchpriority={fetchPriority}
	decoding="async"
	width={intrinsicWidth}
	height={intrinsicHeight}
/>

<style>
	img {
		display: block;
		width: 100%;
		height: auto;
	}
</style>
