<script lang="ts">
	// WebP responsive picture + JPG fallback (640)
	// Fast + simple: ideal for grids / card art

	let {
		src = '',
		alt = '',
		loading = 'lazy',
		fetchPriority = 'auto',
		class: className = '',
		sizes
	} = $props<{
		src?: string;
		alt?: string;
		loading?: 'lazy' | 'eager';
		fetchPriority?: 'high' | 'low' | 'auto';
		class?: string;
		sizes?: string;
	}>();

	// Load intrinsic dimensions generated by your Node script
	// (src/lib/image-sizes.json)
	// eslint-disable-next-line @typescript-eslint/ban-ts-comment
	// @ts-ignore
	import imageMeta from '$lib/image-sizes.json';

	type ImageMeta = Record<
		string,
		{ width: number | null; height: number | null }
	>;

	/*const metaMap = imageMeta as ImageMeta;
	const meta = metaMap[src] ?? null;

	// If missing metadata, fall back to 640x360
	const intrinsicWidth = meta?.width ?? 640;
	const intrinsicHeight = meta?.height ?? Math.round((intrinsicWidth * 9) / 16);
    */

	// /uploads/foo.jpg → /uploads/foo
	const base = src.replace(/\.[^.]+$/, '');

	// WebP srcset
	const webpSrcset = [
		`${base}.320.webp 320w`,
		`${base}.640.webp 640w`,
	].join(', ');

	// Only fallback JPG (640)
	const jpgFallback = `${base}.640.jpg`;

	// Safe default sizes
	const defaultSizes =
		'(min-width: 1200px) 25vw, (min-width: 768px) 33vw, 100vw';
</script>

<picture class={className}>
	<source
		srcset={webpSrcset}
		sizes={sizes ?? defaultSizes}
		type="image/webp"
	>
	<img
		class={className}
		src={jpgFallback}
		alt={alt}
		loading={loading}
		fetchpriority={fetchPriority}
		decoding="async"
		width=640
		height=300
		sizes={sizes ?? defaultSizes}
	>
</picture>

<style>
	img {
		display: block;
		width: 100%;
		height: auto;
		object-fit: cover;
	}
</style>
